name: 'Publish elixir packages to hex.pm by Hipcall'
description: 'Automate publishing packages on Hex.pm'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'activity'
  color: 'orange'